services:
  next_frontend:
      container_name: next_frontend
      image: fabsl22/decathlon_support_system:frontend_v1.1
      build:
        context: ../frontend
        dockerfile: frontend.dockerfile
      environment:
          AUTH_SECRET: k305HdO9r7cxDKx8oxNCQAMqzTIM8ipYvXh/iSr6PYA=
      ports:
        - '3000:3000'
      depends_on:
        - rust_backend
      restart: always
  rust_backend:
      container_name: rust_backend
      image: fabsl22/decathlon_support_system:backend_v1.1
      build:
        context: ../backend
        dockerfile: backend.dockerfile
      env_file: /home/ec2-user/.envs/backend.env
      volumes:
        - /home/ec2-user/.aws:/root/.aws
      ports:
        - '3001:3001'
      restart: always
  reverse_proxy:
    container_name: reverse_proxy
    image: fabsl22/decathlon_support_system:reverse_proxy
    build:
      context: ../deployment
      dockerfile: nginx.dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ec2-user/.certs/:/etc/nginx/ssl:ro
    depends_on:
        - next_frontend
    restart: always
      
